
[ars_nouveau]

	[ars_nouveau.imbuement]
		enable = true

	[ars_nouveau.enchantment]
		enable = true

	[ars_nouveau.enchanting_apparatus]
		enable = true

[maid_storage_manager]

	[maid_storage_manager.smithing]
		enable = true

	[maid_storage_manager.brewing]
		enable = true
		count = 3

	[maid_storage_manager.stripping]
		enable = true

	[maid_storage_manager.tacz]
		enable = true

	[maid_storage_manager.altar]
		enable = true

	[maid_storage_manager.furnace]
		enable = true

	[maid_storage_manager.watering]
		bucket = true
		enable = true
		bottle = true

	[maid_storage_manager.craft]
		enable = true

	[maid_storage_manager.stone_cutting]
		enable = true

